version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      # host 컴퓨터에서는 왼쪽 port로 접속해야하고 같은 네트워크 상의 컨테이너 끼리는 오른쪽 포트로 접근해야한다.
      - 3306:3306
    volumes:
      - "./db/mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 60001:8080

  server:
    build:
      context: ./server
    restart: always
    ports:
      - 60002:18080
    volumes:
      - "./server/home:/root"
    # docker run -it 역할
    # 할당된 표준 입력으로 실행되도록 서비스 컨테이너를 구성
    stdin_open: true
    # TTY와 함께 실행되도록 서비스 컨테이너를 구성
    tty: true
    # 환경변수 설정
    environment:
      - UPBIT_OPEN_API_ACCESS_KEY=${UPBIT_OPEN_API_ACCESS_KEY}
      - UPBIT_OPEN_API_SECRET_KEY=${UPBIT_OPEN_API_SECRET_KEY}
    # networks:
    #   - default
    #   - our_net

networks:
  default:
    external:
      name: our_net
