version: '3.1'
services:
  # db:
  #   image: mariadb:10.5
  #   volumes:
  #     - ./mariadb:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ghost
  #     MYSQL_DATABASE: ghost
  #     MYSQL_USER: ghost
  #     MYSQL_PASSWORD: ghost
  ghost:
    image: ghost:latest
    volumes:
      - ./data:/var/lib/ghost/content
    ports:
      - "60000:2368"
    restart: always
    environment:
      # database__client: mysql
      # database__connection__host: db
      # database__connection__user: ghost
      # database__connection__password: ghost
      # database__connection__database: ghost
      url: http://localhost:60000
